In [1]:
#Thêm thư viện

import tensorflow as tf
import numpy as np

In [2]:
#bai1

t1 = tf.zeros([2, 3])
print("Bài 1:\n", t1)

Bài 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [3]:
#bai2

X = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.zeros_like(X)
print("Bài 2:\n", t2)

Bài 2:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [4]:
#bai3

t3 = tf.fill([3, 2], 5)
print("Bài 3:\n", t3)

Bài 3:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [5]:
#bai4

t4 = tf.linspace(10.0, 12.0, 3, name="linspace")
print("Bài 4:\n", t4)


Bài 4:
 tf.Tensor([10. 11. 12.], shape=(3,), dtype=float32)


In [7]:
#bai5

t5 = tf.range(10, 102, delta=2)
print("Bài 5:\n", t5)

Bài 5:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [10]:
#bai6

t6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print("Bài 6:\n", t6)

Bài 6:
 tf.Tensor(
[[ 2.794647    2.1072028 ]
 [-0.43914336  3.1991038 ]
 [ 5.1624174   1.7860527 ]], shape=(3, 2), dtype=float32)


In [11]:
#bai7

t7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print("Bài 7:\n", t7)

Bài 7:
 tf.Tensor(
[[1.5484388  1.5561333 ]
 [1.7505281  0.01824284]
 [0.69544435 0.8997505 ]], shape=(3, 2), dtype=float32)


In [12]:
#bai8

X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X_8)
print("Bài 8:\n", t8)


Bài 8:
 tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


In [13]:
#bai9

t9_origin = tf.random.normal([10, 10, 3])
t9_cropped = tf.image.random_crop(t9_origin, size=[5, 5, 3])
print("Bài 9 (Kích thước sau khi crop):", t9_cropped.shape)

Bài 9 (Kích thước sau khi crop): (5, 5, 3)


In [14]:
#bai10

x10 = tf.random.uniform([5], minval=1, maxval=10)
y10 = tf.random.uniform([5], minval=1, maxval=10)

print("x =", x10.numpy())
print("y =", y10.numpy())

# Sử dụng tf.where để kiểm tra điều kiện x < y
t10 = tf.where(x10 < y10, x10 + y10, x10 - y10)
print("Bài 10:\n", t10.numpy())

x = [7.149961  5.568963  4.4689407 7.9499855 6.4947357]
y = [7.9968233 7.3428526 6.186001  6.023667  9.890889 ]
Bài 10:
 [15.146784  12.911816  10.654942   1.9263186 16.385624 ]


In [15]:
#bai11

x11 = tf.random.uniform([3, 2], minval=5.0, maxval=10.0)
y11 = tf.random.uniform([2, 3], minval=15.0, maxval=20.0)

# Giữ lại đường chéo của x (xóa các phần tử không thuộc đường chéo chính)
x_diag = tf.linalg.band_part(x11, 0, 0)

# Chuyển vị y thành (3, 2) để có thể cộng với x
y_transpose = tf.transpose(y11)

t11 = x_diag + y_transpose
print("Bài 11:\n", t11.numpy())

Bài 11:
 [[26.153673 18.628826]
 [19.850359 24.502968]
 [18.60407  15.326912]]


In [16]:
#bai12

@tf.function
def compute_ops(x, y):
    return tf.add(x, y), tf.subtract(x, y), tf.multiply(x, y), tf.divide(x, y)

x12 = tf.random.normal([3, 2, 2])
y12 = tf.random.normal([3, 2, 2])

add_res, sub_res, mul_res, div_res = compute_ops(x12, y12)
print("Bài 12 thực thi graph thành công!")

Bài 12 thực thi graph thành công!


In [17]:
#bai13

class SumModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x + y

model_13 = SumModel()
print("Bài 13:", model_13(tf.constant(5), tf.constant(10)).numpy())

Bài 13: 15


In [18]:
#bai14

class DiffProdModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x - y, x * y

model_14 = DiffProdModel()
diff, prod = model_14(tf.constant(8), tf.constant(3))
print("Bài 14 - Hiệu:", diff.numpy(), "Tích:", prod.numpy())

Bài 14 - Hiệu: 5 Tích: 24


In [19]:
#bai15

class RectanglePerimeter(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return (a + b) * 2

model_15 = RectanglePerimeter()
print("Bài 15 (a=3, b=4):", model_15(tf.constant(3), tf.constant(4)).numpy())

Bài 15 (a=3, b=4): 14


In [20]:
#bai16

class BoxSurfaceArea(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        s_xq = (a + b) * c * 2
        s_tp = (a * b) * 2 + s_xq
        return s_tp

model_16 = BoxSurfaceArea()
print("Bài 16 (a=2, b=3, c=4):", model_16(tf.constant(2), tf.constant(3), tf.constant(4)).numpy())

Bài 16 (a=2, b=3, c=4): 52


In [21]:
#bai17

class TrapezoidParallelProof(tf.Module):
    @tf.function
    def __call__(self, AD, BC, AB, CD):
        cond1 = tf.equal(AD, BC)
        cond2 = tf.equal(AB, CD)
        # Trả về True nếu cả 2 điều kiện đều đúng
        return tf.logical_and(cond1, cond2)

model_17 = TrapezoidParallelProof()
print("Bài 17:", model_17(tf.constant(5), tf.constant(5), tf.constant(10), tf.constant(10)).numpy())

Bài 17: True


In [22]:
#bai18

class TrapezoidBaseProof(tf.Module):
    @tf.function
    def __call__(self, AD, BC, is_parallel):
        cond1 = tf.equal(AD, BC)
        return tf.logical_and(cond1, is_parallel)

model_18 = TrapezoidBaseProof()
print("Bài 18:", model_18(tf.constant(4), tf.constant(4), tf.constant(True)).numpy())

Bài 18: True


In [23]:
#bai19

class TriangleMidsegmentProof(tf.Module):
    @tf.function
    def __call__(self, AM, MB, MN, BC):
        # Đường trung bình cần thỏa mãn MN = BC/2
        cond1 = tf.equal(AM, MB)
        cond2 = tf.equal(MN, BC / 2.0)

        return tf.logical_and(cond1, cond2)

model_19 = TriangleMidsegmentProof()
print("Bài 19:", model_19(tf.constant(3.0), tf.constant(3.0), tf.constant(5.0), tf.constant(10.0)).numpy())

Bài 19: True
