In [54]:
#Thêm thư viện cần thiết
import numpy as np
import torch

In [22]:
#bai_1

# Tạo mảng 3x3 với giá trị từ 0 đến 20
arr1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 1:\n", arr1)

# Kiểm tra tất cả các phần tử có khác 0 hay không
is_all_nonzero = np.all(arr1 != 0)
print("Tất cả phần tử khác 0:", is_all_nonzero)

Mảng 1:
 [[15 20 18]
 [ 0 14 10]
 [ 4  2  1]]
Tất cả phần tử khác 0: False


In [23]:
#bai2

arr2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 2:\n", arr2)

is_any_nonzero = np.any(arr2 != 0)
print("Tồn tại phần tử khác 0:", is_any_nonzero)

Mảng 2:
 [[17  3 13]
 [ 6 18  6]
 [ 3  0  8]]
Tồn tại phần tử khác 0: True


In [24]:
#bai3

# Mảng 1 chiều
x1 = np.array([1, 5, 10])
y1 = np.array([2, 5, 8])
print("So sánh 1 chiều (x1 > y1):", np.greater(x1, y1))
print("So sánh 1 chiều (x1 <= y1):", np.less_equal(x1, y1))

# Mảng 2 chiều
x2 = np.array([[1, 2], [3, 4]])
y2 = np.array([[1, 3], [2, 4]])
print("So sánh 2 chiều (x2 >= y2):\n", np.greater_equal(x2, y2))
print("So sánh 2 chiều (x2 < y2):\n", np.less(x2, y2))


So sánh 1 chiều (x1 > y1): [False False  True]
So sánh 1 chiều (x1 <= y1): [ True  True False]
So sánh 2 chiều (x2 >= y2):
 [[ True False]
 [ True  True]]
So sánh 2 chiều (x2 < y2):
 [[False  True]
 [False False]]


In [25]:
#bai4

arr4 = np.concatenate([np.ones(10), np.zeros(10), np.ones(10) * 5])
print("Mảng kết quả:\n", arr4)


Mảng kết quả:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [26]:
#bai5

arr5 = np.arange(30, 71, 2)
print("Mảng số chẵn:\n", arr5)

Mảng số chẵn:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [27]:
#bai6

arr6 = np.identity(3)
print("Ma trận đơn vị 3x3:\n", arr6)


Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#bai7

arr7 = np.random.randint(15, 56, size=10)
print("Mảng ban đầu:", arr7)
print("Bỏ phần tử đầu và cuối:", arr7[1:-1])

Mảng ban đầu: [48 34 41 29 18 20 20 43 32 28]
Bỏ phần tử đầu và cuối: [34 41 29 18 20 20 43 32]


In [29]:
#bai8

arr8 = np.random.randint(0, 21, size=20)
print("Mảng ban đầu:\n", arr8)

# Lọc và đổi dấu
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1
print("Mảng sau khi đổi dấu:\n", arr8)

Mảng ban đầu:
 [16 15 14 17 11 19  8  4 17 15 19 13 17 12  4  9 15 20 14  5]
Mảng sau khi đổi dấu:
 [ 16 -15 -14  17 -11  19   8   4  17 -15  19 -13  17 -12   4  -9 -15  20
 -14   5]


In [30]:
#bai9

arr9 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:\n", arr9)

Ma trận 3x4:
 [[17 20 10 19]
 [17 16 13 13]
 [11 14 14 21]]


In [31]:
#bai10

arr10 = np.ones((10, 10))
arr10[1:-1, 1:-1] = 0
print("Ma trận 10x10:\n", arr10)

Ma trận 10x10:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
#bai11

arr11 = np.diag([1, 2, 3, 4, 5])
print("Ma trận đường chéo:\n", arr11)

Ma trận đường chéo:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [33]:
#bai12

arr12 = np.random.randint(1, 10, size=(3, 3, 3))
print("Tổng theo cột (axis=0):\n", np.sum(arr12, axis=0))
print("Tổng theo dòng (axis=1):\n", np.sum(arr12, axis=1))

Tổng theo cột (axis=0):
 [[17  6 13]
 [16 13 13]
 [19 16 10]]
Tổng theo dòng (axis=1):
 [[14 12 15]
 [17 10  9]
 [21 13 12]]


In [34]:
#bai13

v1 = np.random.randint(1, 10, 10)
v2 = np.random.randint(1, 10, 10)
print("Vector 1:", v1)
print("Vector 2:", v2)
print("Inner product:", np.dot(v1, v2))

Vector 1: [7 7 7 8 9 5 1 9 9 8]
Vector 2: [4 1 6 8 5 6 6 1 8 5]
Inner product: 343


In [35]:
#bai14

A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)
print("Ma trận A:\n", A)
print("Vector y:", y)
print("Kết quả A + y:\n", A + y)

Ma trận A:
 [[8 4 9]
 [1 8 2]
 [8 5 6]
 [6 3 4]]
Vector y: [4 2 6]
Kết quả A + y:
 [[12  6 15]
 [ 5 10  8]
 [12  7 12]
 [10  5 10]]


In [36]:
#bai15

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [37]:
#bai16

df16 = pd.DataFrame({'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]})
first_col_series = df16.iloc[:, 0]
print("Cột đầu tiên dưới dạng Series:\n", first_col_series)

Cột đầu tiên dưới dạng Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [38]:
#bai17

df17 = pd.DataFrame(np.random.randint(1, 20, size=(4, 3)), columns=['A', 'B', 'C'])
print("DataFrame gốc:\n", df17)
print("Sắp xếp theo cột 'B':\n", df17.sort_values(by='B'))

DataFrame gốc:
     A   B   C
0  18  15  15
1   5   1   4
2   5  16   8
3  13  11  15
Sắp xếp theo cột 'B':
     A   B   C
1   5   1   4
3  13  11  15
0  18  15  15
2   5  16   8


In [39]:
#bai18

s18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
s18_reindexed = s18.reindex(['B', 'A', 'C', 'D', 'E'])
print("Series sau khi đổi thứ tự index:\n", s18_reindexed)

Series sau khi đổi thứ tự index:
 B    2
A    1
C    3
D    4
E    5
dtype: int64


In [40]:
#bai19

x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([2, 4, 6, 8, 10])
result19 = x[~x.isin(y)]
print("Các phần tử trong x nhưng không có trong y:\n", result19)

Các phần tử trong x nhưng không có trong y:
 0    1
2    3
4    5
dtype: int64


In [41]:
#bai20

x20 = pd.Series(np.random.randint(1, 30, 20))
y20 = pd.Series(np.random.randint(1, 30, 20))

print("Giao (intersect1d):", np.intersect1d(x20, y20))
print("Hội (union1d):", np.union1d(x20, y20))

Giao (intersect1d): [ 4  6  9 11 12 17 21 24 26 29]
Hội (union1d): [ 1  3  4  6  7  9 11 12 15 17 18 19 20 21 23 24 25 26 27 28 29]


In [42]:
#bai21

sx = pd.Series(['p', 'q', 'r', 'x', 'y'], index=[0, 1, 2, 8, 9])
sy = pd.Series(['a', 'b'], index=[3, 4])

# Theo chiều dọc
vertical = pd.concat([sx, sy], axis=0)
print("Chiều dọc:\n", vertical)

# Theo chiều ngang
horizontal = pd.concat([sx, sy], axis=1)
print("Chiều ngang:\n", horizontal)

Chiều dọc:
 0    p
1    q
2    r
8    x
9    y
3    a
4    b
dtype: object
Chiều ngang:
      0    1
0    p  NaN
1    q  NaN
2    r  NaN
8    x  NaN
9    y  NaN
3  NaN    a
4  NaN    b


In [43]:
#bai22

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_exam = pd.DataFrame(exam_data, index=labels)
print(df_exam)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [44]:
#bai23

print(df_exam.head(3))

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [45]:
#bai24

print(df_exam[['name', 'score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [46]:
#bai25

print(df_exam[df_exam['attempts'] > 2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [47]:
#bai26

print("Số dòng, số cột:", df_exam.shape)

Số dòng, số cột: (10, 4)


In [48]:
#bai27

print(df_exam[df_exam['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [49]:
#bai28

print(df_exam[df_exam['score'].between(15, 20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


In [51]:
#bai29

condition = (df_exam['attempts'] > 2) & (df_exam['score'].between(15, 20))
print(df_exam[condition])

      name  score  attempts qualify
f  Michael   20.0         3     yes


In [53]:
#bai30

df_exam.loc['d', 'score'] = 19.0
print(df_exam)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes
